
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.2.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.10.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/xerrors"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  version = "1.6.0"

[[constraint]]
  name = "github.com/cespare/xxhash"
  version = "2.1.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.26.5"
